###
@base_url = http://localhost:8080

###

POST {{base_url}}/habitlogs/add
Content-Type: application/json

{
  "HabitValues": [
    {
      "Id": 4,
      "Value": "5"
    }
  ]
}

###

GET {{base_url}}/habitlogs/list

###

PUT {{base_url}}/habitlogs/update
Content-Type: application/json

{
  "HabitValues": [
    {
      "Id": 4,
      "Value": "8"
    }
  ],
  "CreatedDateTime": "2025-11-30T21:33:35.50701Z"
}

###