@base_url=http://localhost:4000

###
POST {{base_url}}/auth/signup

###
POST {{base_url}}/auth/signup
Content-Type: application/json

{
  "name": "Hardik Jain",
  "email": "hardik.j0309@gmail.com",
  "password": "password"
}

###
POST {{base_url}}/auth/token

###
POST {{base_url}}/auth/token
Content-Type: application/json

{
  "grantType": "password",
  "email": "hardik.j0309@gmail.com"
}

###
POST {{base_url}}/auth/token
Content-Type: application/json

{
  "grantType": "password",
  "email": "hardik.j0309@gmail.com",
  "password": "password"
}

###

POST {{base_url}}/auth/token
Content-Type: application/json

{
  "grantType": "refresh_token",
  "refreshToken": "6039670d-480f-46eb-85f3-e2e5c9f1e9a9.ea6227c7-ad4d-4fb8-bec4-b9600f15d365"
}

###

POST {{base_url}}/auth/token
Content-Type: application/json

{
  "grantType": "refresh_token",
  "refreshToken": "xyz"
}